from fixein_traditional_method import *

finetuning = {
"22_2.avi":[find_pupil_area_med_first,define_thresholding9,"3_Clean_Giant"],
"17_5.avi":[find_pupil_area_med_first,define_thresholding4,"3_Clean_Giant"],
"17_3.avi":[find_pupil_area_max_length,define_thresholding4,"3_Clean_Giant"],
"5_6.avi":[find_pupil_area_first_and_end,define_thresholding8,"7_Cloudy_None"],
"8_7.avi":[find_pupil_area_med_first,define_thresholding1,"1_Clear_None"],
"16_1.avi":[find_pupil_area_med_first,define_thresholding6,"1_Clear_None"],
"9_16.avi":[find_pupil_area_med_first,define_thresholding1,"1_Clear_None"],
"2_4.avi":[find_pupil_area_med_first,define_thresholding6,"1_Clear_None"],
"21_11.avi":[find_pupil_area_max_length,define_thresholding6,"1_Clear_None"],
"11_7.avi":[find_pupil_area_med_first,define_thresholding4,"1_Clear_None"],
"10_8.avi":[find_pupil_area_max_length,define_thresholding1,"1_Clear_None"],
"6_2.avi":[find_pupil_area_med_first,define_thresholding6,"1_Clear_None"],
"18_7.avi":[find_pupil_area_med_first,define_thresholding1,"1_Clear_None"],
"6_5.avi":[find_pupil_area_med_first,define_thresholding4,"1_Clear_None"],
"4_12.avi":[find_pupil_area_max_length,define_thresholding10,"1_Clear_None"],
"13_2.avi":[find_pupil_area_med_first,define_thresholding1,"1_Clear_None"],
"2_13.avi":[find_pupil_area_med_first,define_thresholding1,"1_Clear_None"],
"9_18.avi":[find_pupil_area_med_first,define_thresholding1,"1_Clear_None"],
"12_1.avi":[find_pupil_area_med_first,define_thresholding6,"1_Clear_None"],
"19_2.avi":[find_pupil_area_med_first,define_thresholding6,"1_Clear_None"],
"21_4.avi":[find_pupil_area_first_and_end,define_thresholding6,"1_Clear_None"],
"6_13.avi":[find_pupil_area_max_length,define_thresholding6,"1_Clear_None"],
"1_9.avi":[find_pupil_area_med_first,define_thresholding1,"4_Blurry_None"],
"15_1.avi":[find_pupil_area_med_first,define_thresholding6,"4_Blurry_None"],
"11_2.avi":[find_pupil_area_med_first,define_thresholding1,"4_Blurry_None"],
"19_3.avi":[find_pupil_area_first_and_end,define_thresholding3,"4_Blurry_None"],
"12_2.avi":[find_pupil_area_first_and_end,define_thresholding6,"4_Blurry_None"],
"15_7.avi":[find_pupil_area_med_first,define_thresholding8,"4_Blurry_None"],
"9_17.avi":[find_pupil_area_max_length,define_thresholding6,"4_Blurry_None"],
"2_10.avi":[find_pupil_area_first_and_end,define_thresholding8,"4_Blurry_None"],
"16_13.avi":[find_pupil_area_first_and_end,define_thresholding8,"4_Blurry_None"],
"1_1.avi":[find_pupil_area_first_and_end,define_thresholding1,"4_Blurry_None"],
"8_2.avi":[find_pupil_area_med_first,define_thresholding6,"4_Blurry_None"],
"16_2.avi":[find_pupil_area_max_length,define_thresholding10,"4_Blurry_None"],
"15_2.avi":[find_pupil_area_med_first,define_thresholding8,"4_Blurry_None"],
"10_11.avi":[find_pupil_area_first_and_end,define_thresholding4,"9_Cloudy_Giant"],
"7_21.avi":[find_pupil_area_first_and_end,define_thresholding8,"9_Cloudy_Giant"],
"3_16.avi":[find_pupil_area_first_and_end,define_thresholding4,"9_Cloudy_Giant"],
"14_17.avi":[find_pupil_area_first_and_end,define_thresholding2,"6_Blurry_Giant"],
"22_17.avi":[find_pupil_area_med_first,define_thresholding9,"6_Blurry_Giant"],
"19_6.avi":[find_pupil_area_max_length,define_thresholding9,"6_Blurry_Giant"],
"7_15.avi":[find_pupil_area_first_and_end,define_thresholding1,"6_Blurry_Giant"],
"4_1.avi":[find_pupil_area_first_and_end,define_thresholding4,"6_Blurry_Giant"],
"22_1.avi":[find_pupil_area_med_first,define_thresholding9,"6_Blurry_Giant"],
"17_12.avi":[find_pupil_area_first_and_end,define_thresholding4,"6_Blurry_Giant"],
"11_13.avi":[find_pupil_area_first_and_end,define_thresholding4,"6_Blurry_Giant"],
"7_18.avi":[find_pupil_area_med_first,define_thresholding6,"2_Clear_Small"],
"14_22.avi":[find_pupil_area_first_and_end,define_thresholding1,"2_Clear_Small"],
"20_4.avi":[find_pupil_area_max_length,define_thresholding1,"2_Clear_Small"],
"21_12.avi":[find_pupil_area_max_length,define_thresholding3,"2_Clear_Small"],
"14_10.avi":[find_pupil_area_first_and_end,define_thresholding6,"2_Clear_Small"],
"3_19.avi":[find_pupil_area_first_and_end,define_thresholding1,"5_Blurry_Small"],
"13_1.avi":[find_pupil_area_first_and_end,define_thresholding1,"5_Blurry_Small"],
"10_1.avi":[find_pupil_area_first_and_end,define_thresholding8,"5_Blurry_Small"],
"4_2.avi":[find_pupil_area_med_first,define_thresholding9,"5_Blurry_Small"],
"20_7.avi":[find_pupil_area_first_and_end,define_thresholding6,"5_Blurry_Small"],
"12_9.avi":[find_pupil_area_first_and_end,define_thresholding6,"5_Blurry_Small"],
"18_11.avi":[find_pupil_area_med_first,define_thresholding1,"5_Blurry_Small"],
"18_2.avi":[find_pupil_area_med_first,define_thresholding6,"5_Blurry_Small"],
"20_3.avi":[find_pupil_area_first_and_end,define_thresholding10,"5_Blurry_Small"],
"1_4.avi":[find_pupil_area_med_first,define_thresholding1,"5_Blurry_Small"],
"3_21.avi":[find_pupil_area_med_first,define_thresholding3,"5_Blurry_Small"],
"13_9.avi":[find_pupil_area_med_first,define_thresholding4,"5_Blurry_Small"],
"5_10.avi":[find_pupil_area_max_length,define_thresholding1,"8_Cloudy_Small"],
"5_11.avi":[find_pupil_area_med_first,define_thresholding6,"8_Cloudy_Small"],
"8_9.avi":[find_pupil_area_med_first,define_thresholding1,"8_Cloudy_Small"]
}



















finetuning2 = {
"1_1": [find_pupil_area_first_and_end, find_pupil_area_first_and_end, define_thresholding8],
"1_4": [find_pupil_area_first_and_end, find_pupil_area_med_first, define_thresholding8],
"1_9": [find_pupil_area_med_first, find_pupil_area_max_depth, define_thresholding8],
"2_4": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"2_10": [find_pupil_area_max_depth, find_pupil_area_max_length, define_thresholding8],
"2_13": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"3_16": [find_pupil_area_max_depth, find_pupil_area_med_first, define_thresholding9],
"3_19": [find_pupil_area_first_and_end, find_pupil_area_max_length, define_thresholding4],
"3_21": [find_pupil_area_med_first, find_pupil_area_first_and_end, define_thresholding6],
"4_1": [find_pupil_area_first_and_end, find_pupil_area_max_length, define_thresholding1],
"4_2": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding8],
"4_12": [find_pupil_area_first_and_end, find_pupil_area_max_length, define_thresholding8],
"5_6": [find_pupil_area_max_depth, find_pupil_area_first_and_end, define_thresholding8],
"5_10": [find_pupil_area_max_length, find_pupil_area_max_depth, define_thresholding1],
"5_11": [find_pupil_area_max_length_and_depth_product, find_pupil_area_max_depth, define_thresholding6],
"6_2": [find_pupil_area_max_depth, find_pupil_area_max_length, define_thresholding8],
"6_5": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding8],
"6_13": [find_pupil_area_max_depth, find_pupil_area_max_depth, define_thresholding8],
"7_15": [find_pupil_area_first_and_end, find_pupil_area_first_and_end, define_thresholding6],
"7_18": [find_pupil_area_first_and_end, find_pupil_area_max_depth, define_thresholding8],
"7_21": [find_pupil_area_first_and_end, find_pupil_area_max_depth, define_thresholding8],
"8_2": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding8],
"8_7": [find_pupil_area_max_length_and_depth_product, find_pupil_area_max_length, define_thresholding8],
"8_9": [find_pupil_area_first_and_end, find_pupil_area_first_and_end, define_thresholding1],
"9_16": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"9_17": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding10],
"9_18": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding10],
"10_1": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding8],
"10_8": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding8],
"10_11": [find_pupil_area_first_and_end, find_pupil_area_first_and_end, define_thresholding2],
"11_2": [find_pupil_area_first_and_end, find_pupil_area_first_and_end, define_thresholding8],
"11_7": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding8],
"11_13": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding4],
"12_1": [find_pupil_area_max_length_and_depth_product, find_pupil_area_max_length, define_thresholding8],
"12_2": [find_pupil_area_max_length, find_pupil_area_max_length_and_depth_product, define_thresholding8],
"12_9": [find_pupil_area_med_first, find_pupil_area_first_and_end, define_thresholding8],
"13_1": [find_pupil_area_med_first, find_pupil_area_first_and_end, define_thresholding1],
"13_2": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"13_9": [find_pupil_area_max_depth, find_pupil_area_max_length, define_thresholding9],
"14_10": [find_pupil_area_first_and_end, find_pupil_area_first_and_end, define_thresholding8],
"14_17": [find_pupil_area_med_first, find_pupil_area_first_and_end, define_thresholding2],
"14_22": [find_pupil_area_first_and_end, find_pupil_area_first_and_end, define_thresholding8],
"15_1": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"15_2": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"15_7": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"16_1": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"16_2": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"16_13": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"17_3": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding4],
"17_5": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding6],
"17_12": [find_pupil_area_first_and_end, find_pupil_area_med_first, define_thresholding4],
"18_2": [find_pupil_area_med_first, find_pupil_area_first_and_end, define_thresholding8],
"18_7": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding8],
"18_11": [find_pupil_area_first_and_end, find_pupil_area_max_length, define_thresholding1],
"19_2": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"19_3": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"19_6": [find_pupil_area_med_first, find_pupil_area_max_length, define_thresholding4],
"20_3": [find_pupil_area_med_first, find_pupil_area_max_length_and_depth_product, define_thresholding8],
"20_4": [find_pupil_area_max_length, find_pupil_area_max_length, define_thresholding8],
"20_7": [find_pupil_area_first_and_end, find_pupil_area_max_length, define_thresholding10],
"21_4": [find_pupil_area_max_length_and_depth_product, find_pupil_area_max_depth, define_thresholding8],
"21_11": [find_pupil_area_max_depth, find_pupil_area_max_length, define_thresholding8],
"21_12": [find_pupil_area_first_and_end, find_pupil_area_max_length, define_thresholding10],
"22_1": [find_pupil_area_med_first, find_pupil_area_med_first, define_thresholding9],
"22_2": [find_pupil_area_med_first, find_pupil_area_med_first, define_thresholding9],
"22_17": [find_pupil_area_med_first, find_pupil_area_first_and_end, define_thresholding7]
}